### ISSUE TITLE
old pagecake javascript

### ISSUE THREAD

**Issue by xriss** [notshi/bards#1]
head.js or jquery needs to be included somewhere before you can use it.

pagecake had some automated things setup for doing this, but plated will need to be done explicitly.

eg
https://github.com/notshi/bards/blob/master/plated/source/%5E.html#L123

Might be best to just add an external jquery script tag to the main html and then drop all the uses of head.js?

`<script  src="https://code.jquery.com/jquery-3.2.1.min.js"  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="  crossorigin="anonymous"></script>
`

**Comment by xriss** [comment]
or you know, just grab that file and stick it on the website so there are no external dependencies and everything will work when offline.

**Comment by notshi** [comment]
thanks - should have no errors in console now. hopefully.
